### ISSUE TITLE
Oxalis 4.0.3  does not support peppol bis 3.0?

### ISSUE THREAD

**Issue by JokerG** [difi/oxalis#405] opened 2019-01-04 04:58 UTC
Message failed : Combination of receiver (iso6523-actorid-upis::9908:810418052) and document type identifier (busdox-docid-qns::urn:oasis:names:specification:ubl:schema:xsd:Invoice-2::Invoice##urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu:2017:poacc:billing:3.0::) is not supported.

**Comment by HarshaSuranjith** [comment] 2019-02-26 09:43
@klakegg I'm experiencing the same issue with oxalis-standalone v4.0.2

```
Sending failed: no.difi.vefa.peppol.lookup.api.LookupException: Combination of receiver (iso6523-actorid-upis::0192:985206732) and document type identifier (busdox-docid-qns::urn:oasis:names:specification:ubl:schema:xsd:Invoice-2::Invoice##urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu
:2017:poacc:billing:3.0::) is not supported.
```

**Comment by klakegg** [comment] 2019-02-26 09:47
Duplicate of #398. Please make sure to check out closed issues before opening new issues.

**Closed by klakegg** 2019-02-26 09:47 UTC
Labels: Not Oxalis, Support

**Comment by HarshaSuranjith** [comment] 2019-02-26 10:47
Hi @klakegg , 

I`m facing the same issue. But I`m transmitting an SBDH wrapped message. Also I`m using the Oxalis sniffer for extracting info from EHF 3.0 documents.

This is the exception thrown when transmitting the message.
```
WARNING: Sending failed: no.difi.vefa.peppol.lookup.api.LookupException: Combination of receiver (iso6523-actorid-upis::0192:985206732) and document type identifier (busdox-docid-qns::urn:oasis:names:specification:ubl:schema:xsd:Invoice-2::Invoice##urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu
:2017:poacc:billing:3.0::) is not supported.
```

**Comment by klakegg** [comment] 2019-02-26 10:52
Still a duplicate of #398.

**Comment by HarshaSuranjith** [comment] 2019-02-26 10:57
@klakegg, I`m wrapping the document before transmitting. So its different from case in 398.

**Comment by klakegg** [comment] 2019-02-26 11:13
Then your wrapping is wrong because of #398.

**Comment by HarshaSuranjith** [comment] 2019-02-26 11:57
Hi @klakegg,

Thanks for the quick  response.

I`m using Oxalis sniffer for constructing the SBDH, I understand its being deprecated, but what I don't understand is how SBDH becomes incompatible for EHF-3, just because sniffer its being deprecated. There was a problem with new ICD values, but I implemented a workaround for that. Here is the generated SBDH.

```
<StandardBusinessDocumentHeader>
        <HeaderVersion>1.0</HeaderVersion>
        <Sender>
            <Identifier Authority="iso6523-actorid-upis">9908:985206732</Identifier>
        </Sender>
        <Receiver>
            <Identifier Authority="iso6523-actorid-upis">9908:810304642</Identifier>
        </Receiver>
        <DocumentIdentification>
            <Standard>urn:oasis:names:specification:ubl:schema:xsd:CreditNote-2</Standard>
            <TypeVersion>2.1</TypeVersion>
            <InstanceIdentifier>c277464f-c6ae-474b-9efd-aeb1a85051c1</InstanceIdentifier>
            <Type>CreditNote</Type>
            <CreationDateAndTime>2019-02-26T14:26:27.638+05:30</CreationDateAndTime>
        </DocumentIdentification>
        <BusinessScope>
            <Scope>
                <Type>DOCUMENTID</Type>
                <InstanceIdentifier>
                    urn:oasis:names:specification:ubl:schema:xsd:CreditNote-2::CreditNote##urn:www.cenbii.eu:transaction:biitrns014:ver2.0:extended:urn:www.peppol.eu:bis:peppol5a:ver2.0:extended:urn:www.difi.no:ehf:kreditnota:ver2.0::2.1
                </InstanceIdentifier>
            </Scope>
            <Scope>
                <Type>PROCESSID</Type>
                <InstanceIdentifier>urn:www.cenbii.eu:profile:bii05:ver2.0</InstanceIdentifier>
            </Scope>
        </BusinessScope>
    </StandardBusinessDocumentHeader>
```

can you help me figure out what's wrong here ?

**Comment by klakegg** [comment] 2019-02-26 14:22
This is off topic and related to the reason we are deprecating document sniffing.
