### ISSUE TITLE
uploading sample xml to Difi's test access point (Content does not contain SBDH.)

### ISSUE THREAD

**Issue by vincentpwnz00r** [difi/oxalis#469] opened 2020-04-23 08:22 UTC
I am getting this error `Message failed : Content does not contain SBDH.` when I run the test. I understand that it needs to wrap the document with SBDH wrapper before being able to run for the test. But how do i go about doing it ?

**Comment by madhawag** [comment] 2020-04-23 15:13
@vincentpwnz00r ,

You could externally use *oxalis-document-sniffer* dependency to wrap your
document payload with SBDH headers.
"no.difi.oxalis" % "oxalis-document-sniffer" % "4.0.2"

In SbdhWrapper class you could find the below method which does that.

public byte[] wrap(InputStream inputStream, Header headers)

I have also mentioned about this in the case  https://github.com/difi/oxalis/issues/451

**Comment by klakegg** [comment] 2020-04-23 17:38
Duplicate of #451

**Closed by klakegg** 2020-04-23 17:38 UTC
Labels: Legacy component

**Comment by kukel** [comment] 2020-06-17 20:44
You get this same error if you have very small typos in the documents. Oxalis is not the best in reporting the real issue. A line break in a namepace declaration already caused this error.
