### ISSUE TITLE
Unable to detect production mode for certificate with new PEPPOL certificate

### ISSUE THREAD

**Issue by sindrehi** [difi/oxalis#396] opened 2018-12-06 13:01 UTC
Hi,

We get the following error when we try to install new V3 certificate:
06-Dec-2018 13:24:56.620 SEVERE [main] org.apache.catalina.core.StandardContext.filterStart Exception starting filter [guiceFilter]
 com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, no.difi.vefa.peppol.common.lang.PeppolLoadingException: Unable to detect mode for certificate 'C=NO, O=Dcode Websolutions AS, OU=PEPPOL PRODUCTION AP, CN=PNO000192'.
  at no.difi.oxalis.commons.mode.ModeModule.providesMode(ModeModule.java:49)
  while locating no.difi.vefa.peppol.mode.Mode
    for the 3rd parameter of no.difi.oxalis.inbound.servlet.StatusServlet.<init>(StatusServlet.java:58)
  at no.difi.oxalis.inbound.servlet.StatusServlet.class(StatusServlet.java:58)
  while locating no.difi.oxalis.inbound.servlet.StatusServlet

2018-12-06 13:24:56,572 INFO [no.difi.vefa.peppol.security.ModeDetector] [] Detection error (TEST): Validation of subject principal(CN) failed. 
2018-12-06 13:24:56,616 INFO [no.difi.vefa.peppol.security.ModeDetector] [] Detection error (PRODUCTION): Certification path could not be validated. 

Our Oxalis version is 4.02. I see in other threads that 4.03 is mentioned, but cant find this version in Maven repository

Edit: We upgraded to 4.03 and get same result

**Comment by monze** [comment] 2018-12-06 14:16
Version 4.0.3 has been released in Maven. Try look here : https://mvnrepository.com/artifact/no.difi.oxalis/oxalis-inbound

Jacob Mogensen
mySupply Aps

**Comment by sindrehi** [comment] 2018-12-06 14:22
We noticed after adding issue here. So upgrade is already done, and we get the exact same error as before

**Comment by klakegg** [comment] 2018-12-06 14:40
"Certification path could not be validated."
Where may I find the certificate?

**Comment by sindrehi** [comment] 2018-12-06 15:13
We added path to the PCKS#12 in config file. You can see from error message that Certificate Key store is loaded. We dont have a special path to certificate other than to the PCKS#12 file
Certificate was enrolled from PEPPOL ( https://openpeppol.atlassian.net/wiki/spaces/OPMA/pages/399016013/Enrollment+with+Firefox+version+56 ). If needed we can send p12 file secured outside github.

**Comment by magjohan** [comment] 2018-12-07 13:10
Here is our sertificate.

[peppol_aws_2018.zip](https://github.com/difi/oxalis/files/2657331/peppol_aws_2018.zip)

**Comment by sindrehi** [comment] 2018-12-07 13:15
> "Certification path could not be validated."
> Where may I find the certificate?


[oxalis_cert_export_all.zip](https://github.com/difi/oxalis/files/2657326/oxalis_cert_export_all.zip)


> Here is our sertificate.
> 
> [peppol_aws_2018.zip](https://github.com/difi/oxalis/files/2657331/peppol_aws_2018.zip)

Hi,

OK, I could possibly look at the certificate to see if it was diferent from our, but without password we cant look at it.
[oxalis_cert.zip](https://github.com/difi/oxalis/files/2657357/oxalis_cert.zip)

Here is a copy of our certificate with password 123Dc0de!

**Comment by jannewaren** [comment] 2018-12-07 13:24
I did not really look into the files you posted but this worries me a bit. You should probably not post your certificate AND password here. This is the thing you should keep as a very important secret, right?? Anyone can act as you in the PEPPOL network now.

You should get a new certificate and not leak it again.

**Comment by sindrehi** [comment] 2018-12-07 13:31
I agree. But we can reissue certificate after. Problem here is that there was a question to send certificate here on github so it could be investigated if it was something wrong with it.

[oxalis_cert.zip](https://github.com/difi/oxalis/files/2657391/oxalis_cert.zip)

**Comment by klakegg** [comment] 2018-12-07 13:32
The code running in Oxalis performing detection is duplicated in the following test:

```java
public class CertTest {

    @Test
    public void simple01() throws IOException, CertificateValidationException, PeppolLoadingException {
        X509Certificate certificate;

        // prod-cert.crt is provided production certificate
        try (InputStream inputStream = getClass().getResourceAsStream("/prod-cert.crt")) {
            certificate = Validator.getCertificate(inputStream);
        }
        Mode mode = ModeDetector.detect(certificate);

        System.out.println(mode.getIdentifier());
    }
}
```

Dependencies:
https://mvnrepository.com/artifact/no.difi.vefa/peppol-security/1.1.1
https://mvnrepository.com/artifact/org.testng/testng/6.14.3 (test)

Environment: Oracle Java 8.0_161

The test returns the following expected result:

```log
[2018-12-07 14:24:22][INFO ][main      ][ModeDetector   ]: Detection error (TEST): Validation of subject principal(CN) failed.
PRODUCTION
```

We are not able to reproduce the error in our environment. What is different in my environment compared to yours?

**PS. All certificates in key stores provided must be revoked and reissued.**

**Comment by sindrehi** [comment] 2018-12-07 14:35
We installed 4.03 from maven repository. We will try to build instead from Github now if there might be updates here that is not published in the version we just installed.

**Comment by klakegg** [comment] 2018-12-07 15:07
Random thought: Are you running something else than Java 8?

**Comment by simakas** [comment] 2018-12-07 19:12
@klakegg how to run the test you pasted?

**Comment by sindrehi** [comment] 2018-12-07 19:17
Last update. Tried to build oxalis from version 4.03 and from master version in github. Both gives the same error. No problems starting oxalis with old V2 certificate. Only v3 Certificate dont work. 
We noticed that we have a later build of Java then you had. 8.0.171, Not sure if this could be a problem. 
Code snippet of certTest is the same as in our build from github.

**Comment by simakas** [comment] 2018-12-07 19:21
hey @sindrehi, I think we both are only ones having same issues here. we run Tomcat7, Java 1.8.101, Centos 6. V2 runs just fine, V3 is lost in all possible ways. Managed to generate 11 different test cases with that certificate, nothing makes it work. were you able to run the test @klakegg pasted above?

**Comment by sindrehi** [comment] 2018-12-07 19:40
> hey @sindrehi, I think we both are only ones having same issues here. we run Tomcat7, Java 1.8.101, Centos 6. V2 runs just fine, V3 is lost in all possible ways. Managed to generate 11 different test cases with that certificate, nothing makes it work. were you able to run the test @klakegg pasted above?

No, we are not sure how to run this test. I see @klakegg  added .crt file in test. But we only have the p12 file.

**Comment by simakas** [comment] 2018-12-07 19:42
i suppose it does not matter what kind of cert it is, they previously said pkcs and jks can be used interchangeably. i tried that - i get the same error, so it means they both fail same way.

**Comment by klakegg** [comment] 2018-12-07 20:03
PKCS#12 and JKS files are *key stores*, they contain *certificate(s)*.

Please replace `peppol-securtiy-1.1.1.jar` inside your Oxalis war with the `peppol-security-1.1.2-SNAPSHOT.jar` inside [peppol-security-1.1.2-SNAPSHOT.zip](https://github.com/difi/oxalis/files/2658599/peppol-security-1.1.2-SNAPSHOT.zip) and report back.

**Comment by simakas** [comment] 2018-12-07 20:09
located it in /WEB-INF/lib/. It now does not even start deploying and crashes instantly with

`
Dec 07, 2018 6:22:21 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Error configuring application listener of class no.difi.oxalis.inbound.OxalisGuiceContextListener
java.lang.NoClassDefFoundError: no/difi/vefa/peppol/security/api/CertificateValidator
`

**Comment by simakas** [comment] 2018-12-07 20:13
Im currently compiling and putting Tomcat8 online, will see if that makes any changes. Im totally out of ideas. Peppol docs say something about adding CA's to keystore after downloading, does it makes any sense? I tried that as well, but nothing happened, they are ignored.

**Comment by klakegg** [comment] 2018-12-07 20:40
Please use this complete war (inside zip) instead:
[oxalis.zip](https://github.com/difi/oxalis/files/2658714/oxalis.zip)

**Comment by simakas** [comment] 2018-12-07 21:20
no change:

`
19:33:53.945 [localhost-startStop-1] INFO no.difi.vefa.peppol.security.ModeDetector - Detection error (PRODUCTION): Certification path could not be validated.
Dec 07, 2018 7:33:53 PM org.apache.catalina.core.StandardContext filterStart
SEVERE: Exception starting filter guiceFilter
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, no.difi.vefa.peppol.common.lang.PeppolLoadingException: Unable to detect mode for certificate 'C=NO, O=At Work Systems AS, OU=PEPPOL PRODUCTION AP, CN=PNO000114'.
`

**Comment by simakas** [comment] 2018-12-07 21:34
i moved back to original 4.0.2 release, deployed Tomcat 8 and it finally started..

**Comment by sindrehi** [comment] 2018-12-09 12:45
Testing results:
1) 402 + Klakegg, p12 (v3) - similar error as for simkas (see attached log)
2) 402 + Klakegg, jks (v2) - not starting anymore (some certificate error)
3) 402 (original build from github), p12 (v3) - error which was at the beginning
4) 402 (original build from github), jks (v2) - running
 5) 403 + Klakegg, p12 (v3) - same error as in TestCase 1 (see log). 
 6) 403 (original build from github), p12 (v3) - error which was at the beginnin

"+ Klakegg" -> Copied Klakegg given oxalis.war file in /home/tomcat/apache-tomcat-9.0.8/webapps/oxalis.war 

As I see, @simakas had before tomcat 7 and java 8.101 And they updated tomcat to version 8.
We have tomcat 9 and newer java. Could it be that we have to downgrade Tomcat to 8?

[logs.zip](https://github.com/difi/oxalis/files/2660522/logs.zip)

**Comment by simakas** [comment] 2018-12-09 12:50
hey, @sindrehi - i suggest downgrading to what system requirements say. Historically I also had issues with higher or lower Java versions and higher or lower Tomcat versions. Looks like there are some strict version dependencies in their code. Tried all Tom/Java combos when v3 was released and it only worked with one combo. Looks like the same story continues with v4.

**Comment by sindrehi** [comment] 2018-12-10 09:43
So, we finally made it work.
Since its easier to upgrade, we tried that first, and upgrade from Tomcat 9.0.8 to latest Tomcat 9.0.13 worked. Then it started, but stopped again. After some more checking and testing we noticed that it did not start with validator-web-2.0.2, so when removing this its working perfect. We can deploy validator manually after start and it still works.

**Closed** 2018-12-20 09:55 UTC
Labels: Information missing
