### ISSUE TITLE
Support for PKI V2 and PKI V3

### ISSUE THREAD

**Issue by robrechtD** [difi/oxalis#365] opened 2018-10-09 12:35 UTC
The peppol documentation states that: "All APs MUST be able to support receiving transactions initiated using BOTH available PKI certificates (v2 and v3)." 
I assume we have to support both V2 and V3 certificates on our AP.
I have placed both certificates in one keystore, yet I can only figure out how to support one or the other with the oxalis.keystore.key.alias property in the oxalis.conf file. 
When I select the PKI v3 cert, an error is thrown when trying to transmit files to this AP concerning a mismatch between the AS2 endpoints. i.e. people are attempting to transmit files using our AS2 V2 endpoint (APP000...) and we are only receiving at our AS2 v3 endpoint (PBE000...)

Is it possible to support both certs in one endpoint?
Or is my understanding of the peppol documentation wrong?

_Originally posted by @robrechtD in https://github.com/difi/oxalis/issues/339#issuecomment-428173600_

**Comment by klakegg** [comment] 2018-10-09 14:09
Duplicate of #339.

**Closed by klakegg** 2018-10-09 14:09 UTC

**Comment by robrechtD** [comment] 2018-10-10 08:46
This is indeed a duplicate, but no solution was given in the other issue. 
Oxalis version 4.0.3 was mentioned, but this release is not yet available in maven.
