### ISSUE TITLE
Too Many Connection from MySQL  While Sending the document

### ISSUE THREAD

**Issue by VijayaKumar2** [difi/oxalis#292] opened 2017-06-20 04:05 UTC
Hi All,

We are getting the following exception from MySQL while sending the document via Oxalis outbound.

 Error in custom provider, java.lang.IllegalStateException: Unable to get a connection from the provided datasource\n  at eu.peppol.persistence.guice.RepositoryModule.rawStatisticsRepository(RepositoryModule.java:64)\n  while locating eu.peppol.statistics.RawStatisticsRepository\n    for parameter 1 at eu.peppol.outbound.transmission.SimpleTransmitter.&lt;init&gt;(SimpleTransmitter.java:38)\n  while locating eu.peppol.outbound.transmission.SimpleTransmitter\n\n1 error","detail":"com.google.inject.ProvisionException: Guice provision errors:\n\n1) Error in custom provider, java.lang.IllegalStateException: Unable to get a connection from the provided datasource\n  at eu.peppol.persistence.guice.RepositoryModule.rawStatisticsRepository(RepositoryModule.java:64)\n  while locating eu.peppol.statistics.RawStatisticsRepository\n    for parameter 1 at eu.peppol.outbound.transmission.SimpleTransmitter.&lt;init&gt;(SimpleTransmitter.java:38)\n  while locating eu.peppol.outbound.transmission.SimpleTransmitter\n\n1 error\n\tat com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:987)\n\tat com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)\n\tat eu.peppol.outbound.OxalisOutboundComponent.getSimpleTransmitter(OxalisOutboundComponent.java:80)\n\tat 

We tried to increase the MySQL connection in the mysql server configuration, but still we are facing the same exception. Because internally in the Oxalis layer - OxalisDataSourceFactoryDbcpImpl.java, the JDBC connection pool setting is configured as 100 as max connection and in which 30 is reserved for IDEL connection. And every one hour it is getting released the connection.

Could anyone help us to resolve this issue, is there any configuration internally getting used by oxalis layer for creating that connection pool.

Thanks,
Vijay

**Comment by teedjay** [comment] 2017-06-20 07:27
Have you tried to define your own datasource in the appserver and use the OxalisDataSourceFactoryJndiImpl.java (instead of the fixed DBCP implementation)?

**Comment by VijayaKumar2** [comment] 2017-06-20 08:31
No We didn't try that. Before that we just want to know what is the better way to implement that.

And we are not using that table data, so can't we disable that completely, since we are not using?

Please suggest what is the better way to proceed?

**Comment by VijayaKumar2** [comment] 2017-06-21 14:19
After increasing the MySQL Connection, things are started working for some extend, but the database connection are releasing immediately so once the number of invoices reached that limit again it started failing.

Could you provide any other option which can be done immediately without customizing.

**Comment by klakegg** [comment] 2017-12-03 16:36
Duplicate of #292

**Closed by klakegg** 2017-12-03 16:36 UTC
