### ISSUE TITLE
upgrade to oxalis-3.2.0 causes ERROR: Unable to trust the signer : Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by vikramjit-singh** [difi/oxalis#265] opened 2016-09-28 09:32 UTC
The message sent to AS2 System id APP_1000000xxx on Wed, 28 Sep 2016 05:40:00 +0000 with subject AS2 MDN as you requested has been received.
It has been processed 
The warning/error message is :
ERROR: Unable to trust the signer : Trust anchor for certification path not found.

------=_Part_0_1809192643.1475041200680
Content-Type: message/disposition-notification
Content-Transfer-Encoding: 7bit

Reporting-UA: Oxalis
Disposition: automatic-action/MDN-sent-automatically; processed/ERROR: Unable to trust the signer : Trust anchor for certification path not found.
Original-Recipient: rfc822; APP_1000000xxx
Final-Recipient: rfc822; APP_1000000xxx
Original-Message-ID: 1da5f08b-9601-4278-903b-c4c7d8440c47

eu.peppol.as2.ErrorWithMdnException: ERROR: Unable to trust the signer : Trust anchor for certification path not found.
	at eu.peppol.as2.InboundMessageReceiver.receive(InboundMessageReceiver.java:158) ~[oxalis-as2-3.2.0.jar:na]
	at eu.peppol.inbound.server.AS2Servlet.doPost(AS2Servlet.java:165) ~[AS2Servlet.class:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:641) [servlet-api.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:722) [servlet-api.jar:na]
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113) [guice-servlet-3.0.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [catalina.jar:7.0.26]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.26]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224) [catalina.jar:7.0.26]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169) [catalina.jar:7.0.26]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.26]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168) [catalina.jar:7.0.26]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98) [catalina.jar:7.0.26]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927) [catalina.jar:7.0.26]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.26]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [catalina.jar:7.0.26]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:987) [tomcat-coyote.jar:7.0.26]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:579) [tomcat-coyote.jar:7.0.26]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:307) [tomcat-coyote.jar:7.0.26]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_77]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_77]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_77]
Caused by: java.lang.IllegalStateException: Unable to trust the signer : Trust anchor for certification path not found.
	at eu.peppol.as2.SignedMimeMessageInspector.validateCertificate(SignedMimeMessageInspector.java:211) ~[oxalis-as2-3.2.0.jar:na]
	at eu.peppol.as2.SignedMimeMessageInspector.parseSignedMessage(SignedMimeMessageInspector.java:174) ~[oxalis-as2-3.2.0.jar:na]
	at eu.peppol.as2.SignedMimeMessageInspector.<init>(SignedMimeMessageInspector.java:72) ~[oxalis-as2-3.2.0.jar:na]
	at eu.peppol.as2.As2MessageInspector.validate(As2MessageInspector.java:35) ~[oxalis-as2-3.2.0.jar:na]
	at eu.peppol.as2.InboundMessageReceiver.receive(InboundMessageReceiver.java:104) ~[oxalis-as2-3.2.0.jar:na]
	... 25 common frames omitted
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at org.bouncycastle.jce.provider.PKIXCertPathValidatorSpi.engineValidate(Unknown Source) ~[bcprov-jdk15on-1.49.jar:1.49.0]
	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292) ~[na:1.8.0_77]
	at eu.peppol.as2.SignedMimeMessageInspector.validateCertificate(SignedMimeMessageInspector.java:201) ~[oxalis-as2-3.2.0.jar:na]
	... 29 common frames omitted

**Comment by teedjay** [comment] 2016-09-28 10:46
Since both TEST and PROD thrust chains for PEPPOl are included in Oxalis and selectable using properties (oxalis-global.properties) , this will usually happen if you use TEST settings and try to run against PRODUCTION AccessPoint endpoint (or PROD agains TEST).

**Comment by aaron-kumar** [comment] 2016-09-28 12:21
@teedjay  I was about to reply this issue. You were quick one :+1: 

Yes, It happens when somebody is not using Test certificate with TEST setting. 
So we should use TEST setting with test AP certificate and PRODUCTION setting with Production AP certificate

**Comment by klakegg** [comment] 2016-09-28 20:02
@teedjay is correct. I'll close this issue as this is correct and expected behaviour.

**Closed by klakegg** 2016-09-28 20:02 UTC
