### ISSUE TITLE
OXALIS_HOME not used by Oxalis_stand_alone.jar since version 4.02

### ISSUE THREAD

**Issue by PPotappel** [difi/oxalis#360] opened 2018-10-02 10:36 UTC
It looks like Oxalis_stand_alone.jar doesn't use the environment variable OXALIS_HOME anymore to find the .conf and the keystore. 
The application expects a conf-folder at the same level as the folder when oxalis_stand_alone.jar is started.

Is this new behaviour by design?

**Comment by Brummos** [comment] 2018-10-03 10:20
i ran into this issue and i think its by design, but it doesnt work.

this is where the configuration file comes from "oxalis-extension/oxalis-extension-currenthome/src/main/resources/reference.conf"

if you want the old behaviour (only using the HOME_FOLDER), you can simple remove the line with the conf folder and recompile oxalis.

thats what i did and it seems to work.

there is also a paramater for the oxalis.conf to set the conf folder. but this is never used as it skips this conf file and starts looking in OXALIS-HOME/conf directly. think this is a bug and should be fixed.

**Closed** 2018-11-24 10:11 UTC
