### ISSUE TITLE
Content type is case sensivite

### ISSUE THREAD

**Issue by monze** [difi/oxalis#247] opened 2016-04-06 11:19 UTC
This issue was also raised in issue 219, and closed with he comment:
'The Exception is tracked back to code in rt.jar, indicating content-type as lowercase is the de facto standard.'

However, that statement conflict with the fact that content type as case sensitive has been reported as a bug with severity Major: https://java.net/jira/browse/JAX_WS-1176?jql=text%20~%20%22XmlDataContentHandler%22

I see two options. Either wait for Java to fix the bug and release a new version of the jax-ws library, making the content type case insensitive. Or make our own implementation, and thereby making the content type case insensitive.

The implementation of the class containing the bug can be seen here at github: https://github.com/gf-metro/jaxws/blob/282759e2b822078de9ba78c743ed663541c16ead/jaxws-ri/rt/src/main/java/com/sun/xml/ws/encoding/XmlDataContentHandler.java

It should be possible to either extend the class and override the isXml(..) method and thereby fixing the problem, or simply copy the hole class and work on a local modified version of the class.

Jacob Mogensen
mySupply ApS
Denmark

**Comment by klakegg** [comment] 2017-12-03 16:50
Duplicate of #219.

**Closed by klakegg** 2017-12-03 16:50 UTC
